CREATE TABLE USERS
(
    ID      INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME    VARCHAR (30) NOT NULL ,
    SURNAME VARCHAR (30) NOT NULL ,
    EMAIL   VARCHAR (30) NOT NULL ,
    AGE     INT (10) NOT NULL
);

CREATE TABLE ROLES
(
    ID   INT NOT NULL AUTO_INCREMENT,
    ROLE VARCHAR (10) NOT NULL
);


CREATE TABLE AUTHENTICATE
(
    ID      INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LOGIN          VARCHAR (30) NOT NULL,
    PASSWORD       VARCHAR (30) NOT NULL,
    ROLEID INT NOT NULL DEFAULT 2,
    PROFILE_ENABLE VARCHAR NOT NULL  DEFAULT 'ON',
    FOREIGN KEY(ROLEID) REFERENCES ROLES(ID)
);



CREATE TABLE USER_ROLES
(
    ID      INT NOT NULL AUTO_INCREMENT,
    USER_ID INT NOT NULL ,
    ROLE_ID INT NOT NULL
);
